version: "3.8"

services:
  vue-js:
    container_name: vue-js
    build: .
    ports:
      - 8080:8080 
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:


