name: Unit Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Yarn
      run: yarn install
        
    - name: Build
      run: yarn build

    - name: Gather Coverage
      run: yarn run test:unit