name: Unit Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Docker
      run: docker-compose up
        
    - name: Create Coverage
      run: docker exec -it vue-js yarn test:unit